/** Declaration file generated by dts-gen */

export = mustache_express;

declare function mustache_express(directory?: string, extension?: string): any;

declare namespace mustache_express {
    const prototype: {
    };

}

